logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
  - type: console
  - backup_count: 5
    filename: openssl_tools.log
    max_bytes: 10485760
    type: file
  level: INFO
  schema_version: '1.0'
