#include "api_endpoints.h"
#include "wifi_handler.h"
#include "bpm_detector.h"
#include "bpm_flatbuffers.h"
#include "config.h"
#include <WebServer.h>
#include <flatbuffers/flatbuffers.h>
#include <WiFi.h>

// Global references for legacy support (will be removed in future)
extern WebServer* server;
extern BPMDetector* bpmDetector;

// Internal state for dependency injection
static WebServer* g_server = nullptr;
static BPMDetector* g_bpmDetector = nullptr;

/**
 * API Endpoints Implementation
 *
 * Generated by MCP-Prompts `/esp32-bpm-api-endpoint`
 * Configuration:
 * - endpoint_path: /api/v1/bpm
 * - data_format: flatbuffers
 * - update_rate: 10 Hz
 */

// BPM Current Status Endpoint
void handleBpmCurrent() {
    BPMDetector* detector = g_bpmDetector ? g_bpmDetector : bpmDetector;
    WebServer* srv = g_server ? g_server : server;
    
    if (detector == nullptr || srv == nullptr) {
        if (srv) {
            srv->send(500, "application/json", "{\"error\":\"BPM detector not initialized\"}");
        }
        return;
    }

    // Create FlatBuffers BPM update
    flatbuffers::FlatBufferBuilder builder(1024);

    // Get current BPM data
    auto bpmData = detector->detect();
    auto bpmUpdateOffset = BPMFlatBuffers::createBPMUpdate(
        bpmData.bpm,
        bpmData.confidence,
        bpmData.signal_level,
        sparesparrow::bpm::DetectionStatus::DETECTING,
        builder
    );

    auto binaryData = BPMFlatBuffers::serializeBPMUpdate(bpmUpdateOffset, builder);

    // Send as JSON response (WebServer has limited binary support)
    // TODO: Implement proper binary streaming when WebSocket is added
    String json = "{";
    json += "\"bpm\":" + String(bpmData.bpm, 1) + ",";
    json += "\"confidence\":" + String(bpmData.confidence, 2) + ",";
    json += "\"signal_level\":" + String(bpmData.signal_level, 2) + ",";
    json += "\"status\":\"" + String(bpmData.status) + "\",";
    json += "\"timestamp\":" + String(bpmData.timestamp);
    json += "}";

    srv->send(200, "application/json", json);
}

// BPM Spectrum Analysis Endpoint
void handleBpmSpectrum() {
    WebServer* srv = g_server ? g_server : server;
    if (srv) {
        srv->send(200, "application/json", "{\"spectrum\":\"not_implemented\"}");
    }
}

// System Status Endpoint
void handleSystemStatus() {
    // Create FlatBuffers status update
    flatbuffers::FlatBufferBuilder builder(1024);

    // Send as JSON response for compatibility
    String json = "{";
    json += "\"uptime_seconds\":" + String(millis() / 1000) + ",";
    json += "\"free_heap_bytes\":" + String(ESP.getFreeHeap()) + ",";
    json += "\"cpu_usage_percent\":25,";
    json += "\"wifi_rssi\":" + String(WiFi.status() == WL_CONNECTED ? WiFi.RSSI() : -100);
    json += "}";

    WebServer* srv = g_server ? g_server : server;
    if (srv) {
        srv->send(200, "application/json", json);
    }
}

// Configuration Endpoint
void handleConfiguration() {
    String json = "{";
    json += "\"sample_rate\":" + String(SAMPLE_RATE) + ",";
    json += "\"fft_size\":" + String(FFT_SIZE) + ",";
    json += "\"min_bpm\":" + String(MIN_BPM) + ",";
    json += "\"max_bpm\":" + String(MAX_BPM) + ",";
    json += "\"detection_threshold\":" + String(DETECTION_THRESHOLD) + ",";
    json += "\"confidence_threshold\":" + String(CONFIDENCE_THRESHOLD);
    json += "}";

    WebServer* srv = g_server ? g_server : server;
    if (srv) {
        srv->send(200, "application/json", json);
    }
}

// Health Check Endpoint
void handleHealth() {
    String json = "{";
    json += "\"status\":\"ok\",";
    json += "\"uptime\":" + String(millis()) + ",";
    json += "\"heap\":" + String(ESP.getFreeHeap()) + ",";
    json += "\"wifi_connected\":" + String(WiFi.status() == WL_CONNECTED ? "true" : "false");
    json += "}";

    WebServer* srv = g_server ? g_server : server;
    if (srv) {
        srv->send(200, "application/json", json);
    }
}

// WebSocket Handler (placeholder for real-time streaming)
void handleWebSocket() {
    WebServer* srv = g_server ? g_server : server;
    if (srv) {
        srv->send(200, "application/json", "{\"websocket\":\"not_implemented\"}");
    }
}

/**
 * Initialize API Endpoints with dependency injection
 *
 * Sets up all REST endpoints for BPM data access
 */
void setupApiEndpoints(WebServer* server_instance, BPMDetector* detector) {
    if (server_instance == nullptr) {
        DEBUG_PRINTLN("[API] Error: WebServer instance is null");
        return;
    }
    
    // Store references for handlers
    g_server = server_instance;
    g_bpmDetector = detector;
    
    // BPM endpoints
    server_instance->on("/api/v1/bpm/current", HTTP_GET, handleBpmCurrent);
    server_instance->on("/api/v1/bpm/spectrum", HTTP_GET, handleBpmSpectrum);

    // System endpoints
    server_instance->on("/api/v1/system/status", HTTP_GET, handleSystemStatus);
    server_instance->on("/api/v1/system/config", HTTP_GET, handleConfiguration);
    server_instance->on("/api/v1/system/health", HTTP_GET, handleHealth);

    // WebSocket endpoint (future)
    server_instance->on("/ws", HTTP_GET, handleWebSocket);

    DEBUG_PRINTLN("API endpoints initialized:");
    DEBUG_PRINTLN("  GET /api/v1/bpm/current - Current BPM data (FlatBuffers)");
    DEBUG_PRINTLN("  GET /api/v1/bpm/spectrum - Audio spectrum analysis");
    DEBUG_PRINTLN("  GET /api/v1/system/status - System status (FlatBuffers)");
    DEBUG_PRINTLN("  GET /api/v1/system/config - System configuration");
    DEBUG_PRINTLN("  GET /api/v1/system/health - Health check");
}

/**
 * Legacy initialization (uses global variables)
 * @deprecated Use setupApiEndpoints(WebServer*, BPMDetector*) instead
 */
void setupApiEndpoints() {
    if (server == nullptr || bpmDetector == nullptr) {
        DEBUG_PRINTLN("[API] Warning: Using legacy setupApiEndpoints() - globals may be null");
    }
    setupApiEndpoints(server, bpmDetector);
}
