#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║              SpareTools Cloudsmith Integration               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 Repository URL: https://cloudsmith.io/~sparesparrow-conan/packages/"
echo "🔧 Package Manager: Conan"
echo "📦 Repository: sparesparrow-conan/openssl-conan"
echo ""

echo "📊 CURRENT STATUS:"
echo "═══════════════════════════════════════════════════════════════"

echo "✅ Already Published Packages:"
cloudsmith list packages sparesparrow-conan/openssl-conan --query="sparetools" 2>/dev/null | grep -E "(sparetools-[a-zA-Z-]+)" | wc -l || echo "Unable to query (authentication required)"
echo ""

echo "⏳ Packages Ready for Publishing:"
echo "• sparetools-pentest-toolkit (Penetration testing tools)"
echo "• sparetools-prompt-system (Prompt rendering & web interface)"
echo "• sparetools-sdr-tools (SDR & RF analysis tools)"
echo "• sparetools-streaming-solutions (RTSP/HLS streaming)"
echo "• sparetools-wifi-sensing (CSI processing & motion detection)"
echo ""

echo "🚀 PUBLISHING INSTRUCTIONS:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Set your Cloudsmith API Key:"
echo "   export CLOUDSMITH_API_KEY='your_api_key_here'"
echo "   # Get key from: https://cloudsmith.io/user/settings/api-key/"
echo ""
echo "2. Authenticate:"
echo "   cloudsmith login --api-key \"\$CLOUDSMITH_API_KEY\""
echo ""
echo "3. Publish packages:"
echo "   cd ~/projects/sparetools"
echo "   ./publish_with_cloudsmith_cli.sh"
echo ""
echo "4. Verify publication:"
echo "   ./check_published_packages.sh"
echo ""

echo "🔍 VERIFICATION COMMANDS:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "# Check authentication status"
echo "cloudsmith whoami"
echo ""
echo "# List all sparetools packages"
echo "cloudsmith list packages sparesparrow-conan/openssl-conan --query='sparetools'"
echo ""
echo "# Check specific package"
echo "cloudsmith list packages sparesparrow-conan/openssl-conan --query='sparetools-pentest-toolkit'"
echo ""

echo "📚 INTEGRATION WITH SPARETOOLS:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Once published, other projects can consume these packages by adding to their conanfile.py:"
echo ""
echo "def requirements(self):"
echo "    self.requires('sparetools-pentest-toolkit/1.0.0')"
echo "    self.requires('sparetools-prompt-system/1.0.0')"
echo "    self.requires('sparetools-sdr-tools/1.0.0')"
echo "    self.requires('sparetools-streaming-solutions/1.0.0')"
echo "    self.requires('sparetools-wifi-sensing/1.0.0')"
echo ""

echo "🔧 DEVELOPMENT WORKFLOW:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Make changes to packages in ~/projects/sparetools/packages/"
echo "2. Test locally: conan create packages/pentest/sparetools-pentest-toolkit --build=missing"
echo "3. Publish updates: ./publish_with_cloudsmith_cli.sh"
echo "4. Update version numbers in dependent projects"
echo ""

echo "🌟 BENEFITS:"
echo "═══════════════════════════════════════════════════════════════"
echo "• Centralized package management"
echo "• Versioned dependencies"
echo "• Cross-project reusability"
echo "• Automated distribution"
echo "• Professional package ecosystem"
echo ""

echo "🎯 NEXT STEPS:"
echo "1. Get Cloudsmith API key"
echo "2. Run publishing script"
echo "3. Update dependent projects to use published packages"
echo "4. Set up automated publishing in CI/CD"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                   Ready for Publishing! 🎉                   ║"
echo "╚══════════════════════════════════════════════════════════════╝"
