#pragma once

#include <WebServer.h>

// Forward declarations
class BPMDetector;

/**
 * API Endpoints Header
 *
 * Generated by MCP-Prompts `/esp32-bpm-api-endpoint`
 * Provides REST API endpoints for BPM data access
 */

// Setup API endpoints with dependency injection
void setupApiEndpoints(WebServer* server, BPMDetector* bpmDetector);

// Legacy function for backward compatibility (uses globals)
void setupApiEndpoints();
