blank_issues_enabled: false
contact_links:
  - name: SpareTools Discussions
    url: https://github.com/sparesparrow/sparetools/discussions
    about: Ask questions or share ideas outside of issue tracking.

