#!/bin/bash

# Clone all sparesparrow repos created in 2025

REPOS=(
    "1984"
    "anthropic-tools"
    "awesome-cursor-mpc-server"
    "awesome-mcp-servers"
    "btc-pay-server"
    "bzeed-mobility"
    "claude-desktop-debian"
    "cliphist-android"
    "codemcp"
    "cpy-tools"
    "crewAI"
    "cursor-audio-notifications"
    "cursor-rules"
    "ddp-rs"
    "elevenlabs-agents"
    "esp32-bpm-detector"
    "extension-template-full"
    "extension-template-minimal"
    "extension-template-webview"
    "flight-rs"
    "fuzz-corpora"
    "github-events"
    "honeybot"
    "human-action"
    "L1B3RT4S"
    "libcurl"
    "mcp-cypress-tool"
    "mcp-fbs"
    "mcp-project-orchestrator"
    "mcp-prompts"
    "mcp-prompts-aidl"
    "mcp-prompts-catalog"
    "mcp-prompts-contracts"
    "mcp-prompts-esp32"
    "mcp-prompts-pg"
    "mcp-prompts-rs"
    "mcp-prompts-ts"
    "mcp-prompts-vscode"
    "mcp-router"
    "mcp-servers"
    "mcp-shell-server"
    "mcp-transport-telegram"
    "MCPServer.cpp"
    "NucleusESP32"
    "OmniParser"
    "openssl"
    "openssl-conan-base"
    "openssl-crypto-policies-test"
    "openssl-fips-policy"
    "openssl-profiles"
    "openssl-test"
    "openssl-tools"
    "podman-desktop"
    "podman-desktop-extension-ai-lab"
    "podman-desktop-extension-mcp"
    "podman-desktop-mcp"
    "rtp-midi"
    "rust-network-mgr"
    "siem"
    "sparrow-ai-hero"
    "sparrow-ai-tech"
    "TinyMCP"
    "TinyZero"
    "wcgw"
    "xdocursor"
    "zigbeendicate-sounds"
)

cd ~/projects

for repo in "${REPOS[@]}"; do
    if [ ! -d "$repo" ]; then
        echo "Cloning $repo..."
        git clone "git@github.com:sparesparrow/$repo.git"
    else
        echo "Repo $repo already exists, skipping..."
    fi
done

echo "All repos cloned!"