#!/bin/bash
# Setup Conan environment variables for user/channel configuration

set -e

# Default values
DEFAULT_CONAN_USER="sparesparrow"
DEFAULT_CONAN_CHANNEL="stable"

# Get values from environment or use defaults
CONAN_USER="${CONAN_USER:-$DEFAULT_CONAN_USER}"
CONAN_CHANNEL="${CONAN_CHANNEL:-$DEFAULT_CONAN_CHANNEL}"

# Validate user/channel format
if ! [[ "$CONAN_USER" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "Error: Invalid CONAN_USER format. Must match ^[a-zA-Z0-9_-]+$"
    exit 1
fi

if ! [[ "$CONAN_CHANNEL" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
    echo "Error: Invalid CONAN_CHANNEL format. Must match ^[a-zA-Z0-9_.-]+$"
    exit 1
fi

# Export environment variables
export CONAN_USER="$CONAN_USER"
export CONAN_CHANNEL="$CONAN_CHANNEL"

# Create .env file if it doesn't exist
ENV_FILE=".conan-env"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << EOF
# Conan User/Channel Configuration
# Generated by setup-conan-env.sh
CONAN_USER=$CONAN_USER
CONAN_CHANNEL=$CONAN_CHANNEL
EOF
    echo "Created $ENV_FILE with user/channel configuration"
fi

# Display configuration
echo "Conan Environment Configuration:"
echo "  User: $CONAN_USER"
echo "  Channel: $CONAN_CHANNEL"
echo ""
echo "Environment variables set. You can now run Conan commands with user/channel support."
echo "Example: conan create . --user=$CONAN_USER --channel=$CONAN_CHANNEL"