#!/usr/bin/env python3
"""
CPY Environment Setup Script

Creates ~/CPY modular Python environment using symlinks to Conan packages.
Supports multiple environments (base, hil, mcp) with layered activation.

Usage:
    python setup-cpy-environment.py --env all      # Install everything
    python setup-cpy-environment.py --env base     # Base only
    python setup-cpy-environment.py --env hil      # Base + HIL
    python setup-cpy-environment.py --clean        # Remove installation
    python setup-cpy-environment.py --validate hil # Validate environment
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional, Dict, List


class ConanPackageResolver:
    """Resolve Conan package references to filesystem paths"""

    @staticmethod
    def get_package_folder(package_ref: str) -> Optional[Path]:
        """
        Get the package folder path for a Conan package reference.

        Args:
            package_ref: Package reference (e.g., "sparetools-cpy-base/1.0.0")

        Returns:
            Path to package folder, or None if not found
        """
        try:
            result = subprocess.run(
                ["conan", "cache", "path", package_ref],
                capture_output=True,
                text=True,
                check=True
            )
            cache_path = result.stdout.strip()

            # Conan cache path points to export folder, add /p for package folder
            if cache_path.endswith("/e"):
                package_path = Path(cache_path.replace("/e", "/p"))
            else:
                package_path = Path(cache_path) / "p"

            if package_path.exists():
                return package_path

            print(f"⚠️  Package folder not found: {package_path}")
            return None

        except subprocess.CalledProcessError as e:
            print(f"❌ Error resolving package {package_ref}: {e.stderr}")
            return None
        except Exception as e:
            print(f"❌ Unexpected error: {e}")
            return None


class SymlinkTreeCreator:
    """Create symlink trees preserving directory structure"""

    @staticmethod
    def create_directory_symlink(source: Path, target: Path) -> bool:
        """
        Create a directory symlink.

        Args:
            source: Source directory (must exist)
            target: Target symlink path (will be created)

        Returns:
            True if successful, False otherwise
        """
        try:
            if target.exists() or target.is_symlink():
                if target.is_symlink() and target.resolve() == source.resolve():
                    print(f"  ↺ Symlink already exists: {target} → {source}")
                    return True
                else:
                    print(f"  ⚠️  Removing existing: {target}")
                    if target.is_symlink():
                        target.unlink()
                    elif target.is_dir():
                        shutil.rmtree(target)
                    else:
                        target.unlink()

            # Create parent directories
            target.parent.mkdir(parents=True, exist_ok=True)

            # Create symlink
            target.symlink_to(source, target_is_directory=True)
            print(f"  ✅ Created symlink: {target} → {source}")
            return True

        except Exception as e:
            print(f"  ❌ Failed to create symlink: {e}")
            return False


class ActivationScriptGenerator:
    """Generate shell activation scripts from templates"""

    @staticmethod
    def generate_base_script(cpy_root: Path) -> bool:
        """Generate activate-base.sh script"""
        script_path = cpy_root / "scripts" / "activate-base.sh"
        script_path.parent.mkdir(parents=True, exist_ok=True)

        script_content = f"""#!/bin/bash
# CPY Base Environment Activation Script
# Auto-generated by setup-cpy-environment.py

# Save original environment
export _CPY_OLD_PATH="$PATH"
export _CPY_OLD_PYTHONPATH="${{PYTHONPATH:-}}"
export _CPY_OLD_PYTHONHOME="${{PYTHONHOME:-}}"
export _CPY_OLD_PS1="${{PS1:-}}"

# Set CPY base environment
export PYTHONHOME="{cpy_root}/base"
export PATH="{cpy_root}/base/bin:$PATH"
export LD_LIBRARY_PATH="{cpy_root}/base/lib:${{LD_LIBRARY_PATH:-}}"
export PYTHONPATH="{cpy_root}/base/lib/python3.12:{cpy_root}/base/shared_dev_tools"

# Update prompt
export PS1="(cpy-base) $PS1"
export _CPY_BASE_ACTIVE=1

echo "✅ CPY base environment activated (Python 3.12.7)"
"""

        try:
            with open(script_path, 'w') as f:
                f.write(script_content)
            script_path.chmod(0o755)
            print(f"  ✅ Generated: {script_path}")
            return True
        except Exception as e:
            print(f"  ❌ Failed to generate base script: {e}")
            return False

    @staticmethod
    def generate_hil_script(cpy_root: Path) -> bool:
        """Generate activate-hil.sh script"""
        script_path = cpy_root / "scripts" / "activate-hil.sh"

        script_content = f"""#!/bin/bash
# CPY HIL Environment Activation Script
# Auto-generated by setup-cpy-environment.py

# Source base if not active
if [ -z "$_CPY_BASE_ACTIVE" ]; then
    source "{cpy_root}/scripts/activate-base.sh"
fi

# Add HIL site-packages to PYTHONPATH (prepend for priority)
export PYTHONPATH="{cpy_root}/envs/hil/lib/python3.12/site-packages:$PYTHONPATH"

# HIL-specific environment variables
export CPY_ENV="hil"
export PYTEST_TIMEOUT=300
export CAN_INTERFACE="vcan0"

# Update prompt (replace cpy-base with cpy-hil)
export PS1="(cpy-hil) ${{PS1#(cpy-base) }}"
export _CPY_HIL_ACTIVE=1

echo "✅ CPY HIL environment activated (pytest, python-can, pyserial)"
"""

        try:
            with open(script_path, 'w') as f:
                f.write(script_content)
            script_path.chmod(0o755)
            print(f"  ✅ Generated: {script_path}")
            return True
        except Exception as e:
            print(f"  ❌ Failed to generate HIL script: {e}")
            return False

    @staticmethod
    def generate_deactivate_script(cpy_root: Path) -> bool:
        """Generate deactivate.sh script"""
        script_path = cpy_root / "scripts" / "deactivate.sh"

        script_content = """#!/bin/bash
# CPY Environment Deactivation Script
# Auto-generated by setup-cpy-environment.py

# Restore original environment
if [ -n "$_CPY_OLD_PATH" ]; then
    export PATH="$_CPY_OLD_PATH"
fi
if [ -n "$_CPY_OLD_PYTHONPATH" ]; then
    export PYTHONPATH="$_CPY_OLD_PYTHONPATH"
else
    unset PYTHONPATH
fi
if [ -n "$_CPY_OLD_PYTHONHOME" ]; then
    export PYTHONHOME="$_CPY_OLD_PYTHONHOME"
else
    unset PYTHONHOME
fi
if [ -n "$_CPY_OLD_PS1" ]; then
    export PS1="$_CPY_OLD_PS1"
fi

# Clear CPY markers
unset _CPY_BASE_ACTIVE _CPY_HIL_ACTIVE _CPY_MCP_ACTIVE
unset _CPY_OLD_PATH _CPY_OLD_PYTHONPATH _CPY_OLD_PYTHONHOME _CPY_OLD_PS1
unset CPY_ENV PYTEST_TIMEOUT CAN_INTERFACE
unset LD_LIBRARY_PATH

echo "✅ CPY environment deactivated"
"""

        try:
            with open(script_path, 'w') as f:
                f.write(script_content)
            script_path.chmod(0o755)
            print(f"  ✅ Generated: {script_path}")
            return True
        except Exception as e:
            print(f"  ❌ Failed to generate deactivate script: {e}")
            return False


class CpyEnvironmentSetup:
    """Main setup orchestrator"""

    def __init__(self, cpy_root: Optional[Path] = None):
        self.cpy_root = cpy_root or Path.home() / "CPY"
        self.metadata_dir = self.cpy_root / ".cpy-metadata"
        self.resolver = ConanPackageResolver()
        self.symlink_creator = SymlinkTreeCreator()
        self.script_generator = ActivationScriptGenerator()

    def setup_base(self) -> bool:
        """Setup base CPython environment"""
        print("\n" + "=" * 60)
        print("Setting up CPY base environment")
        print("=" * 60)

        # Resolve cpy-base package (try with and without channel)
        cpy_base_folder = self.resolver.get_package_folder("sparetools-cpy-base/1.0.0")
        if not cpy_base_folder:
            # Try without channel
            print("  ℹ️  Trying to find package without channel...")
            result = subprocess.run(
                ["conan", "list", "sparetools-cpy-base/1.0.0:*"],
                capture_output=True,
                text=True
            )
            if "sparetools-cpy-base/1.0.0" in result.stdout:
                # Package exists, get its path
                result = subprocess.run(
                    ["conan", "cache", "path", "sparetools-cpy-base/1.0.0"],
                    capture_output=True,
                    text=True
                )
                if result.returncode == 0:
                    cache_path = result.stdout.strip()
                    # Find the actual package folder
                    cache_base = Path(cache_path).parent.parent
                    # Look for package folders
                    for item in cache_base.rglob("*/p"):
                        if item.is_dir() and (item / "dependencies.json").exists():
                            cpy_base_folder = item
                            break
        if not cpy_base_folder:
            print("❌ sparetools-cpy-base/1.0.0 not found. Please build it first:")
            print("   conan create packages/foundation/sparetools-cpy-base --build=missing")
            return False

        # Read dependencies.json
        deps_json = cpy_base_folder / "dependencies.json"
        if not deps_json.exists():
            print(f"❌ dependencies.json not found in {cpy_base_folder}")
            return False

        with open(deps_json, 'r') as f:
            deps_info = json.load(f)

        cpython_folder = Path(deps_info["cpython"]["package_folder"])
        shared_dev_tools_folder = Path(deps_info["shared_dev_tools"]["package_folder"])

        print(f"\n📍 CPython location: {cpython_folder}")
        print(f"📍 shared-dev-tools location: {shared_dev_tools_folder}")

        # Create base directory structure
        base_dir = self.cpy_root / "base"
        base_dir.mkdir(parents=True, exist_ok=True)

        # Create symlinks for CPython directories
        for subdir in ["bin", "lib", "include", "share"]:
            source = cpython_folder / subdir
            target = base_dir / subdir
            if source.exists():
                self.symlink_creator.create_directory_symlink(source, target)

        # Create symlink for shared-dev-tools
        target = base_dir / "shared_dev_tools"
        source = shared_dev_tools_folder / "shared_dev_tools"
        if source.exists():
            self.symlink_creator.create_directory_symlink(source, target)

        # Generate activation scripts
        print("\n📝 Generating activation scripts...")
        self.script_generator.generate_base_script(self.cpy_root)
        self.script_generator.generate_deactivate_script(self.cpy_root)

        # Save metadata
        self._save_metadata("base", {
            "cpy_base_folder": str(cpy_base_folder),
            "cpython_folder": str(cpython_folder),
            "shared_dev_tools_folder": str(shared_dev_tools_folder)
        })

        print("\n✅ Base environment setup complete!")
        print(f"📂 Location: {self.cpy_root}")
        print(f"🔧 Activate: source {self.cpy_root}/scripts/activate-base.sh")

        return True

    def setup_hil(self) -> bool:
        """Setup HIL testing environment"""
        print("\n" + "=" * 60)
        print("Setting up CPY HIL environment")
        print("=" * 60)

        # Ensure base is installed
        if not (self.cpy_root / "base").exists():
            print("❌ Base environment not found. Setting up base first...")
            if not self.setup_base():
                return False

        # Resolve cpy-hil package
        cpy_hil_folder = self.resolver.get_package_folder("sparetools-cpy-hil/1.0.0")
        if not cpy_hil_folder:
            print("❌ sparetools-cpy-hil/1.0.0 not found. Please build it first:")
            print("   conan create packages/testing/sparetools-cpy-hil --build=missing")
            return False

        print(f"\n📍 HIL package location: {cpy_hil_folder}")

        # Create envs/hil directory structure
        hil_dir = self.cpy_root / "envs" / "hil"
        hil_dir.mkdir(parents=True, exist_ok=True)

        # Create symlink to HIL lib directory
        source = cpy_hil_folder / "lib"
        target = hil_dir / "lib"
        if source.exists():
            self.symlink_creator.create_directory_symlink(source, target)

        # Generate HIL activation script
        print("\n📝 Generating HIL activation script...")
        self.script_generator.generate_hil_script(self.cpy_root)

        # Save metadata
        self._save_metadata("hil", {
            "cpy_hil_folder": str(cpy_hil_folder)
        })

        print("\n✅ HIL environment setup complete!")
        print(f"🔧 Activate: source {self.cpy_root}/scripts/activate-hil.sh")

        return True

    def validate(self, env: str = "base") -> bool:
        """Validate environment installation"""
        print("\n" + "=" * 60)
        print(f"Validating CPY {env} environment")
        print("=" * 60)

        # Check base environment
        if not (self.cpy_root / "base" / "bin" / "python3").exists():
            print("❌ Python executable not found in base environment")
            return False

        python_bin = self.cpy_root / "base" / "bin" / "python3"

        # Test Python execution
        print(f"\n🧪 Testing Python execution...")
        try:
            result = subprocess.run([str(python_bin), "--version"], capture_output=True, text=True)
            print(f"   {result.stdout.strip()}")
        except Exception as e:
            print(f"❌ Failed to execute Python: {e}")
            return False

        # Test shared-dev-tools import
        print(f"\n🧪 Testing shared-dev-tools import...")
        shared_dev_tools = self.cpy_root / "base" / "shared_dev_tools"
        try:
            result = subprocess.run(
                [str(python_bin), "-c", f"import sys; sys.path.insert(0, '{shared_dev_tools}'); import shared_dev_tools; print('shared-dev-tools OK')"],
                capture_output=True,
                text=True
            )
            print(f"   {result.stdout.strip()}")
        except Exception as e:
            print(f"❌ Failed to import shared-dev-tools: {e}")
            return False

        # If HIL environment, test HIL packages
        if env == "hil":
            hil_site_packages = self.cpy_root / "envs" / "hil" / "lib" / "python3.12" / "site-packages"
            if not hil_site_packages.exists():
                print("❌ HIL site-packages not found")
                return False

            print(f"\n🧪 Testing HIL package imports...")
            test_packages = ["pytest", "can", "serial", "hypothesis", "yaml", "behave"]
            for pkg in test_packages:
                try:
                    result = subprocess.run(
                        [str(python_bin), "-c", f"import sys; sys.path.insert(0, '{hil_site_packages}'); import {pkg}; print('{pkg} OK')"],
                        capture_output=True,
                        text=True
                    )
                    print(f"   {result.stdout.strip()}")
                except Exception as e:
                    print(f"❌ Failed to import {pkg}: {e}")
                    return False

        print("\n✅ Validation passed!")
        return True

    def clean(self) -> bool:
        """Remove CPY installation"""
        print("\n" + "=" * 60)
        print("Cleaning CPY environment")
        print("=" * 60)

        if not self.cpy_root.exists():
            print(f"ℹ️  Nothing to clean: {self.cpy_root} does not exist")
            return True

        try:
            shutil.rmtree(self.cpy_root)
            print(f"✅ Removed: {self.cpy_root}")
            return True
        except Exception as e:
            print(f"❌ Failed to remove {self.cpy_root}: {e}")
            return False

    def _save_metadata(self, env: str, data: Dict) -> None:
        """Save environment metadata"""
        self.metadata_dir.mkdir(parents=True, exist_ok=True)
        metadata_file = self.metadata_dir / f"{env}.json"

        with open(metadata_file, 'w') as f:
            json.dump(data, f, indent=2)

        print(f"  💾 Saved metadata: {metadata_file}")


def main():
    parser = argparse.ArgumentParser(description="Setup CPY modular Python environment")
    parser.add_argument("--env", choices=["all", "base", "hil", "mcp"], default="base",
                        help="Environment to setup (default: base)")
    parser.add_argument("--clean", action="store_true",
                        help="Remove CPY installation")
    parser.add_argument("--validate", choices=["base", "hil", "mcp"],
                        help="Validate environment")
    parser.add_argument("--cpy-root", type=Path,
                        help="CPY root directory (default: ~/CPY)")

    args = parser.parse_args()

    setup = CpyEnvironmentSetup(cpy_root=args.cpy_root)

    if args.clean:
        return 0 if setup.clean() else 1

    if args.validate:
        return 0 if setup.validate(args.validate) else 1

    # Setup environments
    if args.env in ["all", "base"]:
        if not setup.setup_base():
            return 1

    if args.env in ["all", "hil"]:
        if not setup.setup_hil():
            return 1

    print("\n" + "=" * 60)
    print("✅ CPY environment setup complete!")
    print("=" * 60)
    print(f"\n📂 Location: {setup.cpy_root}")
    print(f"🔧 Usage:")
    print(f"   source {setup.cpy_root}/scripts/activate-base.sh    # Activate base")
    print(f"   source {setup.cpy_root}/scripts/activate-hil.sh     # Activate HIL")
    print(f"   source {setup.cpy_root}/scripts/deactivate.sh       # Deactivate")

    return 0


if __name__ == "__main__":
    sys.exit(main())
